### ISSUE TITLE
Refactor examples to ES6

### ISSUE THREAD

**Issue by dotaitch** [nhn/tui.color-picker#26]
## TODO
* [x] README, getting-started
* [ ] `@example` in jsdoc
* [ ] API Examples
  * [ ] apply babel for API Examples
